/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProofRegistry {
  export type ProofRecordStruct = {
    prover: AddressLike;
    requestCount: BigNumberish;
    budgetLimit: BigNumberish;
    timestamp: BigNumberish;
    commitmentHash: BytesLike;
    txHashesRoot: BytesLike;
  };

  export type ProofRecordStructOutput = [
    prover: string,
    requestCount: bigint,
    budgetLimit: bigint,
    timestamp: bigint,
    commitmentHash: string,
    txHashesRoot: string
  ] & {
    prover: string;
    requestCount: bigint;
    budgetLimit: bigint;
    timestamp: bigint;
    commitmentHash: string;
    txHashesRoot: string;
  };
}

export interface ProofRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProof"
      | "getUserProofCount"
      | "getUserProofs"
      | "proofs"
      | "submitAndVerify"
      | "totalProofsVerified"
      | "userProofs"
      | "verifier"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofVerified"): EventFragment;

  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getUserProofCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProofs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "proofs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "submitAndVerify",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProofsVerified",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userProofs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserProofCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAndVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProofsVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userProofs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    proofId: BytesLike,
    prover: AddressLike,
    requestCount: BigNumberish,
    budgetLimit: BigNumberish,
    txHashesRoot: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proofId: string,
    prover: string,
    requestCount: bigint,
    budgetLimit: bigint,
    txHashesRoot: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proofId: string;
    prover: string;
    requestCount: bigint;
    budgetLimit: bigint;
    txHashesRoot: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProofRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProofRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProof: TypedContractMethod<
    [proofId: BytesLike],
    [ProofRegistry.ProofRecordStructOutput],
    "view"
  >;

  getUserProofCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserProofs: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  proofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string, string] & {
        prover: string;
        requestCount: bigint;
        budgetLimit: bigint;
        timestamp: bigint;
        commitmentHash: string;
        txHashesRoot: string;
      }
    ],
    "view"
  >;

  submitAndVerify: TypedContractMethod<
    [
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish],
      _pubSignals: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ],
    [string],
    "nonpayable"
  >;

  totalProofsVerified: TypedContractMethod<[], [bigint], "view">;

  userProofs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [proofId: BytesLike],
    [ProofRegistry.ProofRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserProofCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserProofs"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string, string] & {
        prover: string;
        requestCount: bigint;
        budgetLimit: bigint;
        timestamp: bigint;
        commitmentHash: string;
        txHashesRoot: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitAndVerify"
  ): TypedContractMethod<
    [
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish],
      _pubSignals: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalProofsVerified"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userProofs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;

  filters: {
    "ProofVerified(bytes32,address,uint256,uint256,bytes32,uint256)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
  };
}
