/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proofRegistrySol from "./ProofRegistry.sol";
export { Groth16Verifier__factory } from "./Groth16Verifier__factory";
