/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proofRegistrySol from "./ProofRegistry.sol";
export type { proofRegistrySol };
export type { Groth16Verifier } from "./Groth16Verifier";
export * as factories from "./factories";
export { Groth16Verifier__factory } from "./factories/Groth16Verifier__factory";
export type { IGroth16Verifier } from "./ProofRegistry.sol/IGroth16Verifier";
export { IGroth16Verifier__factory } from "./factories/ProofRegistry.sol/IGroth16Verifier__factory";
export type { ProofRegistry } from "./ProofRegistry.sol/ProofRegistry";
export { ProofRegistry__factory } from "./factories/ProofRegistry.sol/ProofRegistry__factory";
