/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGroth16Verifier__factory } from "./IGroth16Verifier__factory";
export { ProofRegistry__factory } from "./ProofRegistry__factory";
